### ISSUE TITLE
README.md is not showing up in Crates.io

### ISSUE THREAD

**Issue by Mintype** [cynecx/dyncast#1]
Hey! So I was on your Crates.io page and noticed that there was no README.md! Furthermore, I went over to your GitHub page for this crate and saw that there _was_ indeed a README.md. I am including a screenshot of what I see.
![image](https://github.com/cynecx/dyncast/assets/96578565/b0a6b49c-65d3-4371-b46d-729f7d096e7a)

**Comment by cynecx** [comment]
Hi :) Thanks for letting me know but that is quite intentional since that crate (`dyncast-impl`) is an implementation detail of the main crate (i.e. it is not intended for direct use).
